import { Recomendacao, ServicoFinanceiro } from "@/types";

const servicos: ServicoFinanceiro[] = [
  {
    id: "sv-1",
    provedor_id: "prov-1",
    provedor_nome: "BIC",
    nome: "Crédito Pessoal BIC",
    tipo: "credito",
    descricao: "Crédito pessoal para qualquer finalidade com taxas a partir de 13.5% ao ano.",
    taxa_juro_anual: 13.5,
    prazo_minimo_meses: 6,
    prazo_maximo_meses: 60,
    montante_minimo: 50000,
    montante_maximo: 5000000,
    rendimento_minimo: 80000,
    score_credito_minimo: 350,
    requer_conta_bancaria: true,
    ativo: true,
    criado_em: "2025-01-15T08:00:00Z",
    atualizado_em: "2025-06-01T10:00:00Z",
  },
  {
    id: "sv-2",
    provedor_id: "prov-2",
    provedor_nome: "Millennium BCP",
    nome: "Crédito Habitação",
    tipo: "credito",
    descricao: "Financiamento para aquisição de habitação própria com as melhores condições do mercado.",
    taxa_juro_anual: 11.8,
    prazo_minimo_meses: 12,
    prazo_maximo_meses: 360,
    montante_minimo: 1000000,
    montante_maximo: 50000000,
    rendimento_minimo: 200000,
    score_credito_minimo: 400,
    requer_conta_bancaria: true,
    ativo: true,
    criado_em: "2025-02-10T08:00:00Z",
    atualizado_em: "2025-06-10T10:00:00Z",
  },
  {
    id: "sv-3",
    provedor_id: "prov-3",
    provedor_nome: "Standard Bank",
    nome: "Crédito para Negócio",
    tipo: "credito",
    descricao: "Solução de crédito para expandir o seu negócio com prazos flexíveis.",
    taxa_juro_anual: 16.2,
    prazo_minimo_meses: 12,
    prazo_maximo_meses: 84,
    montante_minimo: 200000,
    montante_maximo: 15000000,
    rendimento_minimo: 150000,
    score_credito_minimo: 380,
    requer_conta_bancaria: true,
    ativo: true,
    criado_em: "2025-03-05T08:00:00Z",
    atualizado_em: "2025-06-15T10:00:00Z",
  },
  {
    id: "sv-4",
    provedor_id: "prov-1",
    provedor_nome: "BIC",
    nome: "Seguro de Vida BIC",
    tipo: "seguro",
    descricao: "Proteção completa para si e para a sua família com cobertura internacional.",
    taxa_juro_anual: 0,
    prazo_minimo_meses: 12,
    prazo_maximo_meses: 0,
    montante_minimo: 15000,
    montante_maximo: 0,
    rendimento_minimo: 0,
    score_credito_minimo: 0,
    requer_conta_bancaria: false,
    ativo: true,
    criado_em: "2025-01-20T08:00:00Z",
    atualizado_em: "2025-06-05T10:00:00Z",
  },
  {
    id: "sv-5",
    provedor_id: "prov-2",
    provedor_nome: "Millennium BCP",
    nome: "Seguro Automóvel",
    tipo: "seguro",
    descricao: "Seguro automóvel com cobertura contra terceiros, danos próprios e assistência 24h.",
    taxa_juro_anual: 0,
    prazo_minimo_meses: 6,
    prazo_maximo_meses: 12,
    montante_minimo: 25000,
    montante_maximo: 0,
    rendimento_minimo: 0,
    score_credito_minimo: 0,
    requer_conta_bancaria: false,
    ativo: true,
    criado_em: "2025-04-01T08:00:00Z",
    atualizado_em: "2025-06-12T10:00:00Z",
  },
  {
    id: "sv-6",
    provedor_id: "prov-3",
    provedor_nome: "Standard Bank",
    nome: "Seguro de Saúde",
    tipo: "seguro",
    descricao: "Cobertura de saúde completa com acesso a rede de hospitais e clínicas parceiras.",
    taxa_juro_anual: 0,
    prazo_minimo_meses: 12,
    prazo_maximo_meses: 12,
    montante_minimo: 20000,
    montante_maximo: 0,
    rendimento_minimo: 0,
    score_credito_minimo: 0,
    requer_conta_bancaria: false,
    ativo: true,
    criado_em: "2025-03-15T08:00:00Z",
    atualizado_em: "2025-06-18T10:00:00Z",
  },
  {
    id: "sv-7",
    provedor_id: "prov-4",
    provedor_nome: "BAI",
    nome: "Crédito Pessoal BAI",
    tipo: "credito",
    descricao: "Crédito pré-aprovado para clientes com conta salário no BAI.",
    taxa_juro_anual: 14.9,
    prazo_minimo_meses: 3,
    prazo_maximo_meses: 48,
    montante_minimo: 30000,
    montante_maximo: 3000000,
    rendimento_minimo: 60000,
    score_credito_minimo: 330,
    requer_conta_bancaria: true,
    ativo: true,
    criado_em: "2025-05-01T08:00:00Z",
    atualizado_em: "2025-06-20T10:00:00Z",
  },
];

export const mockRecomendacoes: Recomendacao[] = [
  {
    id: "rec-1",
    utilizador_id: "user-1",
    perfil_financeiro_id: "perfil-1",
    servico_financeiro_id: "sv-1",
    servico: servicos[0],
    probabilidade_adequacao: 0.94,
    posicao_ranking: 1,
    explicacao: "Este crédito é ideal para si porque o seu rendimento mensal de 180.000 Kz está acima do mínimo exigido e o seu score de crédito é compatível. A taxa de 13.5% é a mais competitiva do mercado para o seu perfil.",
    aceite: false,
    visualizada: true,
    criado_em: "2025-06-25T14:00:00Z",
  },
  {
    id: "rec-2",
    utilizador_id: "user-1",
    perfil_financeiro_id: "perfil-1",
    servico_financeiro_id: "sv-2",
    servico: servicos[1],
    probabilidade_adequacao: 0.87,
    posicao_ranking: 2,
    explicacao: "Recomendamos este crédito à habitação porque o seu perfil financeiro estável e o seu score de crédito indicam que reúne as condições necessárias. O prazo alargado até 360 meses permite prestações mais confortáveis.",
    aceite: false,
    visualizada: true,
    criado_em: "2025-06-25T14:00:00Z",
  },
  {
    id: "rec-3",
    utilizador_id: "user-1",
    perfil_financeiro_id: "perfil-1",
    servico_financeiro_id: "sv-3",
    servico: servicos[2],
    probabilidade_adequacao: 0.76,
    posicao_ranking: 3,
    explicacao: "Este crédito para negócio pode ajudar a expandir a sua actividade. O seu score de crédito é suficiente para a candidatura e os prazos até 84 meses permitem um planeamento adequado.",
    aceite: false,
    visualizada: false,
    criado_em: "2025-06-25T14:00:00Z",
  },
  {
    id: "rec-4",
    utilizador_id: "user-1",
    perfil_financeiro_id: "perfil-1",
    servico_financeiro_id: "sv-4",
    servico: servicos[3],
    probabilidade_adequacao: 0.82,
    posicao_ranking: 4,
    explicacao: "Recomendamos este seguro de vida porque tem dependentes e a protecção da sua família é importante. A cobertura internacional é um diferencial relevante para quem viaja com frequência.",
    aceite: false,
    visualizada: false,
    criado_em: "2025-06-25T14:00:00Z",
  },
  {
    id: "rec-5",
    utilizador_id: "user-1",
    perfil_financeiro_id: "perfil-1",
    servico_financeiro_id: "sv-5",
    servico: servicos[4],
    probabilidade_adequacao: 0.68,
    posicao_ranking: 5,
    explicacao: "Com base na sua localização e necessidades de mobilidade, este seguro automóvel oferece a melhor relação entre cobertura e prémio. A assistência 24h é um bónus importante.",
    aceite: false,
    visualizada: false,
    criado_em: "2025-06-25T14:00:00Z",
  },
  {
    id: "rec-6",
    utilizador_id: "user-1",
    perfil_financeiro_id: "perfil-1",
    servico_financeiro_id: "sv-6",
    servico: servicos[5],
    probabilidade_adequacao: 0.71,
    posicao_ranking: 6,
    explicacao: "Recomendamos este seguro de saúde pelo seu custo-benefício. A rede de hospitais parceiros cobre as principais cidades de Angola, garantindo acesso a cuidados de qualidade.",
    aceite: false,
    visualizada: false,
    criado_em: "2025-06-25T14:00:00Z",
  },
  {
    id: "rec-7",
    utilizador_id: "user-1",
    perfil_financeiro_id: "perfil-1",
    servico_financeiro_id: "sv-7",
    servico: servicos[6],
    probabilidade_adequacao: 0.59,
    posicao_ranking: 7,
    explicacao: "Este crédito pessoal do BAI é uma alternativa viável com condições competitivas. Embora a taxa seja ligeiramente superior, o processo de aprovação é mais rápido para clientes com conta salário.",
    aceite: false,
    visualizada: false,
    criado_em: "2025-06-25T14:00:00Z",
  },
];
